name: make artifacts

on:
  workflow_dispatch:

run-name: make artifacts

jobs:
  artifact1:
    runs-on: self-hosted
    steps:
      - name: Eval artifact1
        run: exit `cat artifact1.txt`

      - name: 'Upload Artifact 1'
        uses: actions/upload-artifact@v4
        with:
          name: artifact1
          path: artifact1.txt
          retention-days: 5

  artifact2:
    runs-on: self-hosted
    steps:
      - name: Eval artifact2
        run: exit `cat artifact2.txt`

      - name: 'Upload Artifact 2'
        uses: actions/upload-artifact@v4
        with:
          name: artifact2
          path: artifact2.txt
          retention-days: 5
