name: make artifacts

on:
  workflow_dispatch:
  push:

run-name: make artifacts

jobs:
  artifact1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Eval artifact1
        run: |
          sleep 10
          exit $(cat artifact1.txt)

      # - name: 'Upload Artifact 1'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: artifact1
      #     path: artifact1.txt
      #     retention-days: 5

      - name: debug info
        run:
          echo "${{ github.sha }}/artifact1"

  artifact2:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Eval artifact2
        run: |
          sleep 10
          exit $(cat artifact2.txt)

      # - name: 'Upload Artifact 2'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: artifact2
      #     path: artifact2.txt
      #     retention-days: 5

      - name: debug info
        run:
          echo "${{ github.sha }}/artifact2"