name: make artifacts

on:
  workflow_dispatch:

run-name: make artifacts

jobs:
  artifact1:
    runs-on: self-hosted
    steps:
      - name: Create artifact1
        run: echo "artifact1.txt" > artifact1.txt

      - name: 'Upload Artifact 1'
        uses: actions/upload-artifact@v4
        with:
          name: artifact1
          path: artifact1.txt
          retention-days: 5

  artifact2:
    runs-on: self-hosted
    steps:
      - name: Create artifact2
        run: echo "artifact2.txt" > artifact2.txt

      - name: 'Upload Artifact 2'
        uses: actions/upload-artifact@v4
        with:
          name: artifact2
          path: artifact2.txt
          retention-days: 5
