on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: environment
        options: 
        - dev
        - stage
        - prod

jobs:
  my_job:
    name: deploy to ${{ inputs.environment }}
    runs-on: ${{ ((inputs.environment == "dev") && "label1" ) || ((inputs.environment == "prod") && "label2" ) }

    steps:
    - name: run
      run: |
        echo "i am on runner ${{ runner.name }}"
