name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: environment
        options: 
        - dev
        - stage
        - prod

run-name: Deploy to ${{ inputs.environment }}

jobs:
  job1:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ${{ ((inputs.environment == 'dev') && 'label1' ) || ((inputs.environment == 'prod') && 'label2' ) || ((inputs.environment == 'stage') && 'label1' ) }}

    steps:
    - name: run
      run: |
        echo "i am on runner ${{ runner.name }}"
