name: pr gate

on:
  pull_request:

run-name: pr gate

jobs:
  check-artifact1:
    runs-on: self-hosted
    steps:
      - name: Wait for tests to succeed
        uses: uplift-ltd/wait-for-workflow-run-action@v2
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.PAT }}

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{secrets.PAT}}
          workflow: artifacts.yml
          name: artifact1
          pr: ${{github.event.pull_request.number}}
          workflow_conclusion: ""

  check-artifact2:
    runs-on: self-hosted
    steps:
      - name: Wait for tests to succeed
        uses: uplift-ltd/wait-for-workflow-run-action@v2
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.PAT }}

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{secrets.PAT}}
          workflow: artifacts.yml
          name: artifact2
          pr: ${{github.event.pull_request.number}}
          workflow_conclusion: ""