name: make artifacts

on:
  pull_request:

run-name: make artifacts

jobs:
  check-artifact1:
    runs-on: self-hosted
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: artifacts.yml
          name: artifact1
          branch: ${{ github.base_ref }}

  check-artifact2:
    runs-on: self-hosted
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: artifacts.yml
          name: artifact2
          branch: ${{ github.base_ref }}