name: pr gate

on:
  pull_request:

run-name: pr gate

jobs:
  check-artifact1:
    runs-on: self-hosted
    steps:
      - uses: explorium-ai/wait-github-status-action@v1.0.2
        with:
          name: wait
          token: ${{ secrets.PAT }}
          sha: ${{ github.event.pull_request.head.sha }} # Must

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{secrets.PAT}}
          workflow: artifacts.yml
          name: artifact1
          pr: ${{github.event.pull_request.number}}
          workflow_conclusion: ""

  check-artifact2:
    runs-on: self-hosted
    steps:
      - uses: explorium-ai/wait-github-status-action@v1.0.2
        with:
          name: wait
          token: ${{ secrets.PAT }}
          sha: ${{ github.event.pull_request.head.sha }} # Must

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{secrets.PAT}}
          workflow: artifacts.yml
          name: artifact2
          pr: ${{github.event.pull_request.number}}
          workflow_conclusion: ""